# Generated by Django 6.0.2 on 2026-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="gpa",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="GPA on a 4.0 scale",
                max_digits=4,
            ),
        ),
    ]
