# Generated by Django 6.0.2 on 2026-03-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_studentprofile_gpa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facultyprofile",
            name="name",
        ),
    ]
