# Generated by Django 6.0.2 on 2026-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_department_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
