from rest_framework import viewsets
from drf_spectacular.utils import extend_schema_view, extend_schema, OpenApiResponse
from ..permissions import IsAdmin
from ..models import User
from ..serializers import FacultySerializer


@extend_schema_view(
    list=extend_schema(
        tags=["Faculty"],
        summary="List all faculty members",
        description=(
            "Returns a paginated list of all **active** faculty accounts. "
            "Requires administrator privileges."
        ),
        responses={200: FacultySerializer(many=True)},
    ),
    retrieve=extend_schema(
        tags=["Faculty"],
        summary="Retrieve a faculty member",
        description=(
            "Returns the full profile of a single faculty member identified "
            "by their `college_id`. Requires administrator privileges."
        ),
        responses={
            200: FacultySerializer,
            404: OpenApiResponse(description="Faculty member not found"),
        },
    ),
    create=extend_schema(
        tags=["Faculty"],
        summary="Create a faculty member",
        description=(
            "Creates a new faculty account together with its associated "
            "`faculty_profile`. Password is auto-generated by the custom "
            "manager. Requires administrator privileges."
        ),
        request=FacultySerializer,
        responses={
            201: FacultySerializer,
            400: OpenApiResponse(description="Validation error"),
        },
    ),
    update=extend_schema(
        tags=["Faculty"],
        summary="Update a faculty member (full)",
        description=(
            "Fully replaces all writable fields on a faculty member and their "
            "`faculty_profile`. Requires administrator privileges."
        ),
        request=FacultySerializer,
        responses={
            200: FacultySerializer,
            400: OpenApiResponse(description="Validation error"),
            404: OpenApiResponse(description="Faculty member not found"),
        },
    ),
    partial_update=extend_schema(
        tags=["Faculty"],
        summary="Update a faculty member (partial)",
        description=(
            "Partially updates one or more fields on a faculty member and/or "
            "their `faculty_profile`. All fields are optional. Requires "
            "administrator privileges."
        ),
        request=FacultySerializer,
        responses={
            200: FacultySerializer,
            400: OpenApiResponse(description="Validation error"),
            404: OpenApiResponse(description="Faculty member not found"),
        },
    ),
    destroy=extend_schema(
        tags=["Faculty"],
        summary="Deactivate a faculty member",
        description=(
            "Soft-deletes the faculty member by setting `is_active = False`. "
            "The database row is **never** removed, preserving all related "
            "data. Requires administrator privileges."
        ),
        responses={
            204: OpenApiResponse(description="Faculty member deactivated successfully"),
            404: OpenApiResponse(description="Faculty member not found"),
        },
    ),
)
class FacultyViewSet(viewsets.ModelViewSet):
    serializer_class = FacultySerializer
    lookup_field = "college_id"
    permission_classes = [IsAdmin]

    def get_queryset(self):
        return User.objects.filter(
            role="faculty",
            is_active=True,
        ).select_related("faculty_profile")

    def perform_create(self, serializer):
        data = serializer.validated_data
        user = User.objects.create_faculty(data.copy())
        return user

    def perform_destroy(self, instance):
        # soft delete — never hard delete
        instance.is_active = False
        instance.save()
