from rest_framework import viewsets
from drf_spectacular.utils import extend_schema_view, extend_schema, OpenApiResponse
from ..models import User
from ..serializers import StudentSerializer
from ..permissions import IsAdmin


@extend_schema_view(
    list=extend_schema(
        tags=["Students"],
        summary="List all students",
        description=(
            "Returns a paginated list of all **active** student accounts. "
            "Requires administrator privileges."
        ),
        responses={200: StudentSerializer(many=True)},
    ),
    retrieve=extend_schema(
        tags=["Students"],
        summary="Retrieve a student",
        description=(
            "Returns the full profile of a single student identified by "
            "their `college_id`. Requires administrator privileges."
        ),
        responses={
            200: StudentSerializer,
            404: OpenApiResponse(description="Student not found"),
        },
    ),
    create=extend_schema(
        tags=["Students"],
        summary="Create a student",
        description=(
            "Creates a new student account together with its associated "
            "`student_profile`. Password is auto-generated by the custom "
            "manager. Requires administrator privileges."
        ),
        request=StudentSerializer,
        responses={
            201: StudentSerializer,
            400: OpenApiResponse(description="Validation error"),
        },
    ),
    update=extend_schema(
        tags=["Students"],
        summary="Update a student (full)",
        description=(
            "Fully replaces all writable fields on a student and their "
            "`student_profile`. Requires administrator privileges."
        ),
        request=StudentSerializer,
        responses={
            200: StudentSerializer,
            400: OpenApiResponse(description="Validation error"),
            404: OpenApiResponse(description="Student not found"),
        },
    ),
    partial_update=extend_schema(
        tags=["Students"],
        summary="Update a student (partial)",
        description=(
            "Partially updates one or more fields on a student and/or their "
            "`student_profile`. All fields are optional. Requires administrator privileges."
        ),
        request=StudentSerializer,
        responses={
            200: StudentSerializer,
            400: OpenApiResponse(description="Validation error"),
            404: OpenApiResponse(description="Student not found"),
        },
    ),
    destroy=extend_schema(
        tags=["Students"],
        summary="Deactivate a student",
        description=(
            "Soft-deletes the student by setting `is_active = False`. "
            "The database row is **never** removed, preserving all related "
            "data. Requires administrator privileges."
        ),
        responses={
            204: OpenApiResponse(description="Student deactivated successfully"),
            404: OpenApiResponse(description="Student not found"),
        },
    ),
)
class StudentViewSet(viewsets.ModelViewSet):
    serializer_class = StudentSerializer
    lookup_field = "college_id"
    permission_classes = [IsAdmin]

    def get_queryset(self):
        return User.objects.filter(
            role="student",
            is_active=True,
        ).select_related("student_profile")

    def perform_create(self, serializer):
        data = serializer.validated_data
        user = User.objects.create_student(data.copy())
        return user

    def perform_destroy(self, instance):
        # soft delete — never hard delete
        instance.is_active = False
        instance.save()
